version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - cd frontend && npm install
      - cd ../backend && npm install

  build:
    commands:
      - echo Building the React app...
      - cd frontend && npm run build  # Generates the dist folder
      - cp -R frontend/dist/* backend/public/  # Copy built files to backend public folder
      - echo "React build copied to backend public directory"

  post_build:
    commands:
      - echo Build completed successfully!
      - zip -r quickjobs-app.zip .

artifacts:
  files:
    - quickjobs-app.zip
