version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing backend dependencies..."
      - cd backend && npm install
      - cd ..
      - echo "Installing frontend dependencies..."
      - cd frontend && npm install
  build:
    commands:
      - echo "Building React frontend..."
      - npm run build --prefix frontend
      - echo "Copying build files to backend/public..."
      - rm -rf backend/public
      - mkdir -p backend/public
      - cp -r frontend/dist/* backend/public/
      - echo "Frontend build copied successfully."
artifacts:
  files:
    - backend/**/*  # Includes server, routes, utils, public (built frontend)
    - appspec.yml
    - scripts/**/*
  discard-paths: no
