version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      # Install frontend dependencies
      - cd frontend && npm install
      # Install backend dependencies
      - cd ../backend && npm install

  build:
    commands:
      - echo Building the React app...
      # Build React app
      - cd frontend && npm run build
      # Copy the React build to the backend folder
      - cp -R frontend/build ../backend/public

  post_build:
    commands:
      - echo Build completed successfully!
      - zip -r quickjobs-app.zip .
      
artifacts:
  files:
    - quickjobs-app.zip
